language: generic
dist: xenial
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - cask
  - cask install
env:
  - EVM_EMACS=emacs-26.3-travis-linux-xenial
  - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial
matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

script:
  - emacs --version
  - make compile
  - make test
